AutomatedLab/AutomatedLab.Common

appveyor.yaml
=> Updated appveyor.yaml

AutomatedLab.Common/AutomatedLab.Common.psd1
Added functions to export to module
=> Updated readme

AutomatedLab.Common/AutomatedLab.Common.psd1, AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1, README.md
- Moved the function to AutomatedLab.Common
- Rename from Install-LWSoftwarePackage into Install-SoftwarePackage
- Added code to optionally create a scheduled task with explicit credentials
=> Extended Install-SoftwarePackage

AutomatedLab.Common/AutomatedLab.Common.psd1, README.md, Tests/Get-FullMesh.Tests.ps1, appveyor.yml, psake.ps1
Added a credential parameter to Install-SoftwarePackge to be used when running something as a scheduled task.
=> Added Install-SoftwarePackge

AutomatedLab.Common/AutomatedLab.Common.psd1, AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1, AutomatedLab.Common/Common/Public/Read-Choice.ps1, AutomatedLab.Common/Common/Public/Read-HashTable.ps1, AutomatedLab.Common/Common/Public/Sync-Parameter.ps1, LICENSE
- License is not MIT
- Added function Read-Choice
- Added function Read-HashTable
- Extended Sync-Parameter to work with external scripts
=> Added Read functions and changed license

AutomatedLab.Common/TeamFoundation/Public/Projects/New-TfsProject.ps1
Fixed display bug in New-TfsProject where the error message would be displayed multiple times.
=> Tfs display bug in New-TfsProject fixed

AutomatedLab.Common/Common/Public/Get-DotNetFrameworkVersion.ps1, AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1
- Additional .NET Version to check
- TFS Display bug fixed for New-TfsProject
=> New release

AutomatedLab.Common/AutomatedLab.Common.psd1, AutomatedLab.Common/TeamFoundation/Public/Build/Get-TfsBuildStep.ps1, Build.ps1
- Support for multiple release environments
- Support for build CI triggers and branch filtering
- Support for task conditions according to API version 4.1
=> Enhancement

AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1, AutomatedLab.Common/PkiHelper/Public/Add-Certificate2.ps1, AutomatedLab.Common/PkiHelper/Public/Get-Certificate2.ps1, AutomatedLab.Common/PkiHelper/Types/CertStore.ps1, AutomatedLab.Common/PkiHelper/Types/PkiInternals.ps1
- Rewrite of Add-Certificate2
- Rewrite of Get-Certificate2
- Added class CertificateInfo for better certificate handline
=> CA Cmdlet Improvments

AutomatedLab.Common/AutomatedLab.Common.psm1
Ignore method on module import
=> Executing ServerCertificateValidationCallback

AutomatedLab.Common/Common/Public/Remove-RunspacePool.ps1
Had various issues with Hyper-V labs on PS Core
=> PSCore: Remove-RunspacePool fixed

Library/Pki.CATemplate.cs, Library/Pki.Certificates.cs, Library/Pki.cs
=> Namespace PKI was missing

Library/Gpo.cs
Fixes https://github.com/AutomatedLab/AutomatedLab/issues/660
Tested with a freshly installed VM.
=> GPO: Added error handling around Save method

AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1
On old operating systems the module can be imported, but not without issues. Since the types used make use of features that are newer than .NET 2.0, this module will never fully run on unpatched dinosaur operating systems. With this workaround, Install-SoftwarePackage works again by using a different return type for the exit code that the installation produced.
=> Old OS Workaround

AutomatedLab.Common/DscHelper/Public/Get-DscConfigurationImportedResource.ps1
This fixes AutomatedLab/AutomatedLab#858.
=> Fix for #858 in AutomatedLab

AutomatedLab.Common/Common/Public/Sync-Parameter.ps1, Help/en-us/Sync-Parameter.md
To aid with custom roles that use non-string parameter values
=> Added Conversion parameter to Sync-Parameter

AutomatedLab.Common/Common/Public/New-RunspacePool.ps1, Help/en-us/New-RunspacePool.md
Adding new Function parameter to runspace pool functions
=> Enabling functions in runspace pool

AutomatedLab.Common/Common/Public/Install-SoftwarePackage.ps1
Please describe your changes in detail, unless the title is already descriptive enough.
=> Support WorkingDirectory

AutomatedLab.Common/Common/Public/Get-DotNetFrameworkVersion.ps1
=> Added new .net versions

AutomatedLab.Common/AutomatedLab.Common.psm1
Please describe your changes in detail, unless the title is already descriptive enough.
=> Ensure module can be imported on Linux

AutomatedLab.Common/AutomatedLab.Common.psd1, AutomatedLab.Common/TeamFoundation/Public/Get-TfsBuildStep.ps1, AutomatedLab.Common/TeamFoundation/Public/Get-TfsReleaseStep.ps1, Build.ps1, Help/en-us/Get-ModuleDependency.md
Fixes #132 
Those two cmdlets didn't even work, and were the only reason we were using Newtonsoft.Json in AutomatedLab.Common. Now they work again...
=> Remove Newtonsoft dependency, fix Get-Tfs(Build|Release)Step
